//styles
import './src/styles/style.css'

//scripts
import './src/scripts/01paresImpares.js'
import './src/scripts/02sumarNumeros.js'
import './src/scripts/03numeroMaximo.js'
import './src/scripts/04contarCuantos.js'
import './src/scripts/05numerosPrimos.js'
import './src/scripts/06arrayToStringMayusAlf.js'
import './src/scripts/07sumarDigitos.js'
import './src/scripts/08cuantasLetras.js'
import './src/scripts/09palabraLarga'
import './src/scripts/10invertirCadena.js'
import './src/scripts/11eliminarVocales.js'
import './src/scripts/12contarPalabras.js'
import './src/scripts/13numerosDuplicados.js'
import './src/scripts/14comprobarAnagrama.js'
import './src/scripts/15interseccionArrays.js'
import './src/scripts/16calcularMediana.js'
import './src/scripts/17recursivoFactorial.js'
